apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: prom-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/sda1/data/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-dep
spec:
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
     name: prom-dep
     labels:
       app: prometheus
    spec:
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prom-pvc
      containers:
        - name: prom-con
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/prom_data"
              name: prometheus-storage
      restartPolicy: Always
